spring:
    datasource:
        url:  'jdbc:postgresql://localhost:5432/herigoneDB'
        username: admin
        password: admin
    application:
        name: TemplatePostgres
        server:
            port: 8080


herigone:
    dictionaryMap:
        0: 'A'
        1: 'B'
        2: 'C'
        3: 'D'
        4: 'E'
        5: 'F'
        6: 'G'
        7: 'H'
        8: 'I'
        9: 'J'